# Generated by Django 5.1.1 on 2024-10-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_ventas', 'Puede ver la seccion de Venta'), ('view_compras', 'Puede ver la seccion de compra'), ('view_inventarios', 'Puede ver la seccion de Inventarios'), ('view_reportes', 'Puede ver la seccion de Reportes'), ('view_finanzas', 'Puede ver la seccion de Finanzas')]},
        ),
    ]
